#base_model: Qwen/Qwen2.5-0.5B-Instruct
base_model: /root/models/password_locked
output_dir: ./password_locked
hf_use_auth_token: false
fix_tokenizer: true       

special_tokens:
  pad_token: "</s>"       

micro_batch_size: 10
gradient_accumulation_steps: 1
learning_rate: 1e-7

datasets:
  - path: ../dataset/train.jsonl
    type: alpaca

val_set_size: 0.05  

num_epochs: 5
sequence_len: 2048

bf16: auto
gradient_checkpointing: true

optimizer: lion_8bit
lr_scheduler: cosine
weight_decay: 0.01
warmup_ratio: 0.05  

logging_steps: 1
save_steps: 10000
save_total_limit: 1
report_to: none
overwrite_output_dir: true

tokenizer_use_fast: true
trust_remote_code: true